[package]
name = "rusty-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-escapes = "0.1.1"
ansi_term = "0.12.1"
crossterm = "0.27.0"
rustyline = "14.0.0"
